ADD: Image upload functionality
archivy/archivy pull request #224
Opened 2021-04-14 14:50 UTC by Uzay-G

![random](https://user-images.githubusercontent.com/52892257/114730101-da3f9580-9d40-11eb-93be-cd0120ca2dbf.gif)

Stores image in a `images` subdirectory inside the user directory.

2021-04-14 14:57 UTC, Uzay-G commented
@srevinsaju could you test this out? Thanks :smile:

2021-04-15 16:41 UTC, srevinsaju requested changes
Haven't completely reviewed this yet, but I will look into this PR in a while.

2021-04-15 16:41 UTC, srevinsaju commented on archivy/data.py
> +def image_exists(filename):
Can we add a type hint over here, it looks like it can be both an `int` or a `str`.

2021-04-15 16:41 UTC, srevinsaju commented on archivy/api.py
> +        return jsonify({"error": "415"}), 415
These two can be compressed to just
```python
    return jsonify({"error": "415"}), 415
```

2021-04-15 16:41 UTC, srevinsaju commented on archivy/data.py
> +        return 0
This can be compressed to 
```python
    return 0
```

2021-04-16 14:41 UTC, Uzay-G commented
Ok, I implemented all your suggestions :)

2021-04-17 06:52 UTC, srevinsaju commented
I tried using the Bookmark feature, is it possible to archive / save all of those images to an image file instead of using a link. It might be harder, but it would be a great step to good archive. What do you think?

2021-04-17 13:01 UTC, Uzay-G commented
Oh so you mean bookmarking a link to an image would save it to the images file?

That could be interesting (after this is merged though). Has the image upload function been working though?

2021-04-19 05:35 UTC, srevinsaju commented
> Oh so you mean bookmarking a link to an image would save it to the images directory?


Well, I thought this included this feature too, but what I meant was iterating through all images in a html webpage while scraping and downloading all these images, and saving them in `images/` folder so that these images are still accessible

> 
> That could be interesting (after this is merged though). Has the image upload function been working though?

I just checked out this PR once again. The image upload feature isn't perfect yet. Few things to consider:
* In case the file is huge, the image upload takes a lot of time. This makes the user think that it is a bug. Instead, a progress bar or busy indicator is highly required.
* When trying to upload the image, the `![](..)` markup does not appear immediately. When trying to upload the same image twice, `![](..)` doesn't appear immediately, unless this is attempted many times. On the `nth` time, n \* `![](...)` appears on archivy

![image](https://user-images.githubusercontent.com/48695438/115186308-247e9900-a0ea-11eb-80cf-8bccfef614df.png)

The last line looks like a bug. The same number (i.e. 2) is repeated twice in the file name.

2021-04-19 13:30 UTC, Uzay-G commented
It's not very obvious, but there is actually a progress bar at the bottom (when you upload): 
![image](https://user-images.githubusercontent.com/52892257/115243731-84ddfc80-a123-11eb-808f-1718e149fc97.png)

I haven't had any problems with the speed of uploads :thinking:, especially since the limit (that the editor lib sets by default) is at 2 MB. By the way, do you think I should make that higher / remove it?

For the issue with the ![]() markup being added, I think that just happens if you really mass upload images and the bug you mentioned must just be a timing issue with when images are being saved, in that case.

If everything else works with you @srevinsaju, I'll merge this in and I think I'll add a config option in another PR to save all images found in webpages, like you said.

2021-04-19 13:34 UTC, srevinsaju commented
> It's not very obvious, but there is actually a progress bar at the bottom (when you upload):

Oh, didn't notice that one.

> 
> 
> I haven't had any problems with the speed of uploads , especially since the limit (that the editor lib sets by default) is at 2 MB. By the way, do you think I should make that higher / remove it?

I guess you should remove it, or add a configuration entry to archivy's configuration and let the user keep the cap on the file size.  Preferably setting the default to `-1`, indicating no limit.

> 
> For the issue with the  markup being added, I think that just happens if you really mass upload images and the bug you mentioned must just be a timing issue with when images are being saved, in that case.

This only happens when I try to add the same image multiple times into the editor. Using different filenames does not create this bug.

> 
> If everything else works with you @srevinsaju, I'll merge this in and I think I'll add a config option in another PR to save all images found in webpages, like you said.

I guess its fine.

2021-04-19 13:39 UTC, Uzay-G commented
> I guess you should remove it, or add a configuration entry to archivy's configuration and let the user keep the cap on the file size. Preferably setting the default to -1, indicating no limit.

Good idea.

> This only happens when I try to add the same image multiple times into the editor. Using different filenames does not create this bug.

Yeah, I think there's a timing issue when files with identical filenames are saved repeatedly :thinking:

2021-04-19 14:04 UTC, merged